version: '3.8'
services:
  backend:
    build:
      context: ./backend-test-submission
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend-test-submission:/app
      - /app/node_modules
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/su
      - JWT_SECRET=221601053
    depends_on:
     - mongo
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
  frontend:
    build:
      context: ./frontend-test-submission
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-test-submission:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    depends_on:
      - backend

  